server {
  listen 4174;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  include /etc/nginx/mime.types;
  types {
    text/javascript mjs;
  }

  add_header Cache-Control "no-store";

  location / {
    try_files $uri $uri/ /index.html;
  }
}
